# Generated by Django 2.1 on 2018-08-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your name', max_length=50, verbose_name='Enter your name')),
            ],
        ),
    ]
